# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 Causal-Slash Protocol Developers
"""
Hardcoded Unicode half-block logo strings generated by tools/make_logo.py.
No runtime image or Pillow dependency.
Teal truecolor: #21E2CC (RGB 33, 226, 204).
"""

TEAL_HEX = "#21E2CC"
TEAL_RGB = (33, 226, 204)
TEAL_ANSI = "\033[38;2;33;226;204m"
RESET_ANSI = "\033[0m"

# Main logo (9 lines high: 7-line square glyph + spacer + wordmark)
LOGO_MAIN_RAW = [
    "████████████",
    "◥█          ",
    "████████████",
    "            ",
    "████████████",
    "          ██",
    "████████████",
    "            ",
    "Causal-Slash",
]

# Small logo for /help and compact headers (3 lines high, square proportions)
LOGO_SMALL_RAW = [
    "██████",
    "◥█  ██",
    "██████",
]

# Plain text fallback for terminals without truecolor or UTF-8 block support
LOGO_PLAIN = "Causal-Slash"


def get_logo_lines(small: bool = False, truecolor: bool = True) -> list[str]:
    """Return colored logo lines, or plain text fallback."""
    raw = LOGO_SMALL_RAW if small else LOGO_MAIN_RAW
    if not truecolor:
        return [LOGO_PLAIN]
    return [f"{TEAL_ANSI}{line}{RESET_ANSI}" for line in raw]


def get_logo_rich(small: bool = False):
    """Return logo as rich Text objects with teal truecolor style."""
    from rich.text import Text
    raw = LOGO_SMALL_RAW if small else LOGO_MAIN_RAW
    return [Text(line, style=f"bold {TEAL_HEX}") for line in raw]
