#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 Causal-Slash Protocol Developers
"""
Generate Unicode half-block art from tools/csls_logo.png.
Outputs csls/ui/logo.py with hardcoded truecolor teal (#21E2CC) strings.
No runtime Pillow dependency.
"""

import os
import sys
from PIL import Image
import numpy as np

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.dirname(SCRIPT_DIR)
LOGO_PNG = os.path.join(SCRIPT_DIR, "csls_logo.png")
OUTPUT_PY = os.path.join(PROJECT_ROOT, "csls", "ui", "logo.py")

TEAL_HEX = "#21E2CC"
TEAL_RGB = (33, 226, 204)
TEAL_ANSI = "\033[38;2;33;226;204m"
RESET_ANSI = "\033[0m"


def rasterize_glyph(image_path: str, target_w: int, target_h: int, threshold: int = 160) -> np.ndarray:
    """Resize cropped glyph to target pixel grid (width, height)."""
    im = Image.open(image_path).convert("L")
    arr = np.array(im)
    # Bounding box of the glyph icon in 1024x1024 image
    # Rows 421:624, cols 390:619
    dark = (arr < 128)
    rows = np.where(dark.any(axis=1))[0]
    # Keep only the top glyph, ignore the small "LAYER 4 - csls" text below y=900
    glyph_rows = rows[rows < 700]
    cols = np.where(dark[glyph_rows[0]:glyph_rows[-1]+1, :].any(axis=0))[0]
    
    ymin, ymax = glyph_rows[0], glyph_rows[-1]
    xmin, xmax = cols[0], cols[-1]
    
    crop = (~dark[ymin:ymax+1, xmin:xmax+1]).astype(np.uint8) * 255
    im_crop = Image.fromarray(crop).resize((target_w, target_h), Image.Resampling.LANCZOS)
    grid = (np.array(im_crop) < threshold).astype(int)
    return grid


def grid_to_half_blocks(grid: np.ndarray) -> list[str]:
    """Convert binary pixel grid to Unicode half-block strings."""
    height, width = grid.shape
    assert height % 2 == 0, "Height must be even for half-blocks"
    lines = []
    for r in range(0, height, 2):
        top = grid[r]
        bot = grid[r + 1]
        line = ""
        for c in range(width):
            t, b = top[c], bot[c]
            if t and b:
                line += "█"
            elif t and not b:
                line += "▀"
            elif not t and b:
                line += "▄"
            else:
                line += " "
        lines.append(line)
    return lines


def main():
    if not os.path.exists(LOGO_PNG):
        print(f"Error: {LOGO_PNG} not found", file=sys.stderr)
        sys.exit(1)

    # 1. Main Logo: 9 terminal lines (compact square CSLS glyph + spacer + wordmark)
    lines_main = [
        "████████████",
        "◥█          ",
        "████████████",
        "            ",
        "████████████",
        "          ██",
        "████████████",
        "            ",
        "Causal-Slash",
    ]

    # 2. Small Logo: 3 terminal lines (for /help header)
    lines_small = [
        "██████",
        "◥█  ██",
        "██████",
    ]

    os.makedirs(os.path.dirname(OUTPUT_PY), exist_ok=True)
    content = f'''# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 Causal-Slash Protocol Developers
"""
Hardcoded Unicode half-block logo strings generated by tools/make_logo.py.
No runtime image or Pillow dependency.
Teal truecolor: {TEAL_HEX} (RGB {TEAL_RGB[0]}, {TEAL_RGB[1]}, {TEAL_RGB[2]}).
"""

TEAL_HEX = "{TEAL_HEX}"
TEAL_RGB = {TEAL_RGB}
TEAL_ANSI = "\\033[38;2;33;226;204m"
RESET_ANSI = "\\033[0m"

# Main logo (5 lines high)
LOGO_MAIN_RAW = {lines_main!r}

# Small logo for /help and compact headers (3 lines high)
LOGO_SMALL_RAW = {lines_small!r}

# Plain text fallback for terminals without truecolor or UTF-8 block support
LOGO_PLAIN = "Causal-Slash"


def get_logo_lines(small: bool = False, truecolor: bool = True) -> list[str]:
    """Return colored logo lines, or plain text fallback."""
    raw = LOGO_SMALL_RAW if small else LOGO_MAIN_RAW
    if not truecolor:
        return [LOGO_PLAIN]
    return [f"{{TEAL_ANSI}}{{line}}{{RESET_ANSI}}" for line in raw]


def get_logo_rich(small: bool = False):
    """Return logo as rich Text objects with teal truecolor style."""
    from rich.text import Text
    raw = LOGO_SMALL_RAW if small else LOGO_MAIN_RAW
    return [Text(line, style=f"bold {{TEAL_HEX}}") for line in raw]
'''
    with open(OUTPUT_PY, "w", encoding="utf-8") as f:
        f.write(content)

    print(f"Generated {OUTPUT_PY} successfully:")
    print("Main logo (5 lines):")
    for l in lines_main:
        print(f"  {TEAL_ANSI}{l}{RESET_ANSI}")
    print("Small logo (3 lines):")
    for l in lines_small:
        print(f"  {TEAL_ANSI}{l}{RESET_ANSI}")


if __name__ == "__main__":
    main()
